# -*- coding: utf-8 -*-
"""FInal_upp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VnSTDMmjA4S4BBJPyj7B1fhChBYGK97j
"""

# Step 0 (run first in Colab): install libs (only if needed)
!pip install -q transformers sentence-transformers faiss-cpu rouge-score nltk networkx matplotlib

# Step 1: Imports, device, sample data
# -------------------------
import re, logging, unicodedata, random
from typing import List, Dict, Any, Tuple
import numpy as np
import pandas as pd
import torch
from transformers import pipeline, AutoTokenizer, AutoModelForSeq2SeqLM
from sentence_transformers import SentenceTransformer
import networkx as nx
import matplotlib.pyplot as plt
import nltk
from nltk.tokenize import word_tokenize
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
from rouge_score import rouge_scorer
from sklearn.neighbors import NearestNeighbors
try:
    import faiss
    _HAS_FAISS = True
except Exception:
    _HAS_FAISS = False

logging.basicConfig(level=logging.INFO)
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

sample_texts = [
    "John Doe visited Mayo Clinic on 2023-04-15 complaining of chest pain and was given ibuprofen 200 mg.",
    "My baby has been vomiting and has fever. We visited the pediatric ward at City Health Center on 2022/11/05.",
    "The patient reports dizziness and nausea after taking oxycodone 5 mg twice daily at Green Valley Surgery Center.",
    "Pain under left nipple and stomach pain started on 2021-07-09. Patient record no 67890.",
    "I feel anxious and have depression since yesterday and I ordered tablets from an online pharmacy QuickMeds.",
    "Patient was diagnosed with Type 2 diabetes and hypertension; metformin 500mg prescribed.",
    "She reported migraine and severe headache after the vaccination appointment at Central Hospital.",
    "The oncologist mentioned malignant neoplasm (cancer) and scheduled a biopsy next Monday."
]
df = pd.DataFrame({"input": sample_texts})
print("Loaded", len(df), "samples")

# Step 2: Preprocessing (clean / standardize dates)
# -------------------------
def clean_text(text: str) -> str:
    if not isinstance(text, str):
        return ""
    text = unicodedata.normalize("NFKC", text)
    text = re.sub(r"\s+", " ", text).strip()
    text = re.sub(r"<[^>]+>", " ", text)
    return text.strip(" \t\n\r,.")
def standardize_dates(text: str) -> str:
    text = re.sub(r'\b(\d{1,2})[/-](\d{1,2})[/-](\d{4})\b', r'\3-\1-\2', text)  # dd-mm-yyyy -> yyyy-mm-dd
    text = re.sub(r'\b(\d{4})[/-](\d{1,2})[/-](\d{1,2})\b', r'\1-\2-\3', text)
    return text
df["clean"] = df["input"].apply(lambda x: standardize_dates(clean_text(x)))
print(df["clean"].tolist())

# -------------------------
# Step 3: Load LLM and embedder (one LLM for tasks)
# -------------------------
LLM_MODEL = "google/flan-t5-large"   # change to your biomedical LLM if available
print("Loading LLM:", LLM_MODEL)
tokenizer = AutoTokenizer.from_pretrained(LLM_MODEL)
llm_model = AutoModelForSeq2SeqLM.from_pretrained(LLM_MODEL).to(device)
llm_pipe = pipeline("text2text-generation", model=llm_model, tokenizer=tokenizer,
                    device=0 if device=="cuda" else -1)

EMBED_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
embed_model = SentenceTransformer(EMBED_MODEL, device=device)
print("Loaded embed model:", EMBED_MODEL)

# =======================
# Chunk 4 (UPDATED): Fallback lexicons + dosage-aware merged detector
# REPLACE your old Chunk 4 and Chunk 4b with this block (use same block twice if you had duplicates)
# =======================

# fallback lexicons & regexes (ensure availability before UPP)
COMMON_NAMES = [
    "john","jane","doe","smith","ali","ahmad","peterson","petreson","mike","maria","sara","ahmed"
]
COMMON_PATIENT_TOKENS = ["patient","baby","infant","child","newborn","childrens","kid"]
COMMON_ORGS = [
    "mayo clinic","city health center","green valley surgery center","central hospital","quickmeds",
    "city health","regional hospital","pediatric ward"
]
COMMON_LOCATIONS = ["london","new york","california","islamabad","karachi"]

DISEASE_LEXICON = [
    "cancer","tumor","chest pain","headache","fever","dizziness","nausea",
    "vomiting","depression","anxiety","stomach pain","diabetes","hypertension",
    "migraine","asthma","flu","covid","malignant neoplasm","type 2 diabetes"
]

RE_ID_LONG = re.compile(r'\b\d{5,}\b')
RE_DATE_ISO = re.compile(r'\b(19|20)\d{2}[/-]\d{1,2}[/-]\d{1,2}\b', flags=re.IGNORECASE)
RE_RELATIVE_DATE = re.compile(r'\b(yesterday|today|tomorrow|next monday|last week|next week)\b', flags=re.IGNORECASE)

# DOSAGE pattern: used to detect medication amounts and avoid labeling them as AGE
DOSAGE_PATTERN = re.compile(
    r"\b\d+\s?(mg|mcg|g|gram|grams|kg|ml|mL|L|units|IU|tablet|tablets|capsule|capsules|tab|tabs|pills?|dose|doses|tbsp|mls?)\b",
    flags=re.IGNORECASE
)

def detect_entities_fallback(text: str) -> List[Dict[str, Any]]:
    """
    Heuristic fallback: detect common names, patient tokens, orgs, locations, diseases,
    dates, ids, and medication dosages.
    Returns list of entities in format: {'text':..., 'label':..., 'start':..., 'end':...}
    """
    out = []
    text_low = text.lower()

    # Names & patient tokens
    for name in (COMMON_NAMES + COMMON_PATIENT_TOKENS):
        for m in re.finditer(r'\b' + re.escape(name) + r'\b', text_low, flags=re.IGNORECASE):
            s, e = m.start(), m.end()
            out.append({"text": text[s:e], "label": "PERSON", "start": s, "end": e})

    # Orgs
    for org in COMMON_ORGS:
        for m in re.finditer(re.escape(org), text_low, flags=re.IGNORECASE):
            s, e = m.start(), m.end()
            out.append({"text": text[s:e], "label": "ORG", "start": s, "end": e})

    # Locations
    for loc in COMMON_LOCATIONS:
        for m in re.finditer(r'\b' + re.escape(loc) + r'\b', text_low, flags=re.IGNORECASE):
            s, e = m.start(), m.end()
            out.append({"text": text[s:e], "label": "LOCATION", "start": s, "end": e})

    # Diseases lexicon
    for d in DISEASE_LEXICON:
        for m in re.finditer(r'\b' + re.escape(d) + r'\b', text_low, flags=re.IGNORECASE):
            s, e = m.start(), m.end()
            out.append({"text": text[s:e], "label": "DISEASE", "start": s, "end": e})

    # Dates (ISO-like)
    for m in RE_DATE_ISO.finditer(text):
        s, e = m.start(), m.end()
        out.append({"text": text[s:e], "label": "DATE", "start": s, "end": e})

    # Long numeric IDs
    for m in RE_ID_LONG.finditer(text):
        s, e = m.start(), m.end()
        out.append({"text": text[s:e], "label": "ID", "start": s, "end": e})

    # Dosage detection (mark as DOSAGE so we don't treat them as AGE later)
    for m in DOSAGE_PATTERN.finditer(text):
        s, e = m.start(), m.end()
        out.append({"text": text[s:e], "label": "DOSAGE", "start": s, "end": e})

    # Deduplicate by span+label
    seen = set()
    uniq = []
    for ent in sorted(out, key=lambda x: (x["start"], -x["end"])):
        key = (ent["start"], ent["end"], ent["label"])
        if key not in seen:
            seen.add(key)
            uniq.append(ent)
    return uniq

def postprocess_entities_remove_age_dosage(entities: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """
    Post-process entity list to avoid AGE mislabels:
     - If an entity has label AGE (or NUMBER-like) but overlaps a DOSAGE span or matches DOSAGE_PATTERN,
       relabel it to DOSAGE or remove AGE label.
     - Keep a consistent single label per entity (prefer non-sensitive DOSAGE).
    """
    # first, build an index of dosage spans from entities
    dosage_spans = [(e["start"], e["end"]) for e in entities if e["label"] == "DOSAGE"]
    out = []
    for e in entities:
        lbl = e["label"].upper()
        txt = e["text"]
        s, t = e["start"], e["end"]
        # if labeled AGE but overlaps dosage_span -> treat as DOSAGE
        if lbl in ("AGE", "NUMBER", "NUM"):
            overlaps_dosage = any(not (t <= ds or s >= de) for ds, de in dosage_spans)
            if overlaps_dosage or DOSAGE_PATTERN.search(txt):
                # convert to DOSAGE (non-sensitive for age)
                out.append({"text": e["text"], "label": "DOSAGE", "start": s, "end": t})
                continue
        # if any label (even PERSON/ORG) but the text matches DOSAGE_PATTERN, mark as DOSAGE
        if DOSAGE_PATTERN.search(txt) and lbl != "DOSAGE":
            out.append({"text": e["text"], "label": "DOSAGE", "start": s, "end": t})
            continue
        # otherwise keep original
        out.append(e)
    # dedupe and prefer longer spans when overlapping
    merged_sorted = sorted(out, key=lambda x: (x["start"], -x["end"]))
    final = []
    last_end = -1
    for item in merged_sorted:
        if item["start"] >= last_end:
            final.append(item)
            last_end = item["end"]
        else:
            # overlap: keep longer span
            if item["end"] > final[-1]["end"]:
                final[-1] = item
                last_end = item["end"]
    return final

def detect_entities_final(text: str) -> List[Dict[str, Any]]:
    """
    Wrapper used across pipeline:
      - runs hybrid NER (general + biomed)
      - augments with fallback lexicon detections
      - marks dosages as DOSAGE
      - removes/relables AGE entities that are actually dosages
    Returns deduplicated entities sorted by start.
    """
    # run hybrid detector (general + biomed)
    try:
        base = detect_entities_hybrid(text)
    except Exception:
        base = []

    # get fallback entities
    fallback = detect_entities_fallback(text)

    # merge: prefer base spans, add fallback if new
    merged = []
    covered = set((e["start"], e["end"]) for e in base)
    merged.extend(base)
    for f in fallback:
        if (f["start"], f["end"]) not in covered:
            merged.append(f)

    # Post-process to remove AGE false positives that are dosages
    merged = postprocess_entities_remove_age_dosage(merged)

    # final dedupe: prefer longer spans when overlapping
    merged_sorted = sorted(merged, key=lambda x: (x["start"], -x["end"]))
    final = []
    last_end = -1
    for e in merged_sorted:
        if e["start"] >= last_end:
            final.append(e)
            last_end = e["end"]
        else:
            if e["end"] > final[-1]["end"]:
                final[-1] = e
                last_end = e["end"]
    return final

# For compatibility in other chunks, point generic name to final detector
detect_entities_hf = detect_entities_final

# =======================
# Chunk 5: Relation Extraction (transformer try + heuristic fallback)
# =======================
RE_MODEL = "PaDaS-Lab/privacy-policy-relation-extraction"
use_re_model = True
try:
    re_tokenizer = AutoTokenizer.from_pretrained(RE_MODEL)
    re_model = AutoModelForSequenceClassification.from_pretrained(RE_MODEL).to(device)
    if hasattr(re_model.config, "id2label"):
        re_id2label = re_model.config.id2label
    else:
        re_id2label = {i: str(i) for i in range(re_model.config.num_labels)}
    logging.info("Loaded RE model: %s", RE_MODEL)
except Exception as e:
    logging.warning("RE model not loaded (%s). Using heuristic.", e)
    use_re_model = False
    re_tokenizer = None
    re_model = None
    re_id2label = {}

def extract_relations_transformer(text: str, entities: List[Dict[str, Any]]) -> List[Tuple[str,str,str]]:
    rels = []
    if not use_re_model or len(entities) < 2:
        return rels
    for e1 in entities:
        for e2 in entities:
            if e1 == e2: continue
            marked = (text[:e1["start"]] + "[E1]" + e1["text"] + "[/E1]" + text[e1["end"]:e2["start"]] +
                      "[E2]" + e2["text"] + "[/E2]" + text[e2["end"]:])
            inputs = re_tokenizer(marked, truncation=True, max_length=256, return_tensors="pt").to(device)
            with torch.no_grad():
                out = re_model(**inputs)
                pred = int(torch.argmax(out.logits, dim=1).item())
                lab = re_id2label.get(pred, str(pred))
                if lab and lab.lower() not in ("no_relation","0"):
                    rels.append((e1["text"], lab, e2["text"]))
    return list(set(rels))

def extract_relations_heuristic(text: str, entities: List[Dict[str, Any]]) -> List[Tuple[str,str,str]]:
    rels = []
    s_text = text.lower()
    for e1 in entities:
        for e2 in entities:
            if e1 == e2: continue
            if any(token in s_text for token in ["prescrib", "given", "mg", "tablet", "dose", "dosing"]):
                rels.append((e1["text"], "MEDICATED_WITH", e2["text"]))
            if any(token in s_text for token in ["visit","visited","ward","clinic","appointment"]):
                rels.append((e1["text"], "VISITED", e2["text"]))
            if any(token in s_text for token in ["diagnos","diagnosed","diagnosis"]):
                rels.append((e1["text"], "DIAGNOSED_WITH", e2["text"]))
    return list(set(rels))

def extract_relations(text: str, entities: List[Dict[str, Any]]):
    r = extract_relations_transformer(text, entities)
    if not r:
        r = extract_relations_heuristic(text, entities)
    return r

# =======================
# Chunk 6: Build Knowledge Graph
# =======================
def build_kg_and_nodes(texts: List[str]):
    G = nx.Graph()
    node_texts = []
    for i, t in enumerate(texts):
        doc_node = f"doc:{i}"
        G.add_node(doc_node, label="DOC", text=f"doc_{i}", doc_id=i)
        ents = detect_entities_hf(t)
        for e in ents:
            n = f"{i}:{e['start']}:{e['end']}:{e['text']}"
            if not G.has_node(n):
                G.add_node(n, label=e["label"], text=e["text"], doc_id=i)
                node_texts.append(e["text"])
            G.add_edge(doc_node, n, relation="MENTIONS")
        rels = extract_relations(t, ents)
        for h, r, tt in rels:
            possible_h = [n for n,d in G.nodes(data=True) if d.get("text")==h and d.get("doc_id")==i]
            possible_t = [n for n,d in G.nodes(data=True) if d.get("text")==tt and d.get("doc_id")==i]
            if possible_h and possible_t:
                G.add_edge(possible_h[0], possible_t[0], relation=r, doc_id=i)
    return G, node_texts

G, node_texts = build_kg_and_nodes(df["clean"].tolist())
print("KG nodes:", G.number_of_nodes(), "edges:", G.number_of_edges())

# =======================
# Chunk 7: UPP — Updated module (Age & Area fixes + apply_upp)
# =======================
# Dosage pattern (important: dosages are NOT ages)
dosage_pattern = re.compile(
    r"\b\d+\s?(mg|mcg|g|gram|grams|kg|ml|mL|L|units|IU|tablet|tablets|capsule|capsules|tab|tabs|hour|hours|hr|hrs|dose|doses)\b",
    flags=re.IGNORECASE
)
def is_dosage(text):
    return bool(dosage_pattern.search(text))

# Age mask that does NOT mask dosages
def mask_age(text: str):
    def skip_if_dosage(m):
        match_text = m.group(0)
        if is_dosage(match_text):
            return match_text
        return "[AGE]"
    age_patterns = [
        r"\b\d{1,3}-year-old\b",
        r"\bage\s+\d{1,3}\b",
        r"\b\d{1,3}\s?y/o\b",
        r"\b\d{1,3}\s?years?\s?old\b",
    ]
    for pat in age_patterns:
        text = re.sub(pat, skip_if_dosage, text, flags=re.IGNORECASE)
    return text

# Area/facility masking improved
def mask_area(text: str):
    facility_pattern = re.compile(
        r"\b([A-Z][a-z]+(?:\s+[A-Z][a-z]+){0,3}\s+(Hospital|Clinic|Center|Surgery|Care|Medical|Health))\b",
        flags=re.IGNORECASE
    )
    text = facility_pattern.sub("[AREA]", text)
    area_terms = [
        "Hospital", "Clinic", "Center", "Surgery",
        "Medical Center", "Health Center", "Care Center"
    ]
    for term in area_terms:
        text = re.sub(rf"\b{re.escape(term)}\b", "[AREA]", text, flags=re.IGNORECASE)
    return text

# Final UPP application
def apply_upp_masking_only(text: str) -> str:
    # run entity-aware masking first (to target known spans) + then pattern-based replacements
    ents = detect_entities_hf(text)
    out = text
    # mask by entity spans (reverse order)
    for ent in sorted(ents, key=lambda x: x["start"], reverse=True):
        s, e = ent["start"], ent["end"]
        lbl = ent["label"].upper()
        orig = out[s:e]
        if any(k in lbl for k in ["PERSON","PATIENT","NAME"]):
            out = out[:s] + "[PERSON]" + out[e:]
        elif any(k in lbl for k in ["ORG","HOSPITAL","FACILITY","ORGANIZATION"]):
            out = out[:s] + "[HEALTHCARE_FACILITY]" + out[e:]
        elif any(k in lbl for k in ["LOC","GPE","LOCATION","CITY","AREA"]):
            out = out[:s] + "[AREA]" + out[e:]
        elif any(k in lbl for k in ["DATE","TIME"]):
            # coarsen to year if possible
            ym = re.search(r'\b(19|20)\d{2}\b', orig)
            if ym:
                out = out[:s] + f"[DATE:{ym.group(0)}]" + out[e:]
            else:
                out = out[:s] + "[DATE]" + out[e:]
        elif any(k in lbl for k in ["ID","NUMBER"]) and len(re.sub(r'\s','',orig))>=5:
            out = out[:s] + "[ID]" + out[e:]
        elif "AGE" in lbl:
            # apply mask_age to the substring
            masked = mask_age(orig)
            out = out[:s] + masked + out[e:]
        else:
            # leave other tokens (DISEASE, DRUG, SYMPTOM) unchanged
            pass

    # regex fallbacks after span-level masking
    # protect dosages (do nothing)
    # coarsen ISO dates
    out = re.sub(r'\b(19|20)\d{2}[/-]\d{1,2}[/-]\d{1,2}\b', lambda m: "[DATE:"+re.search(r'\b(19|20)\d{2}\b', m.group(0)).group(0)+"]", out)
    out = re.sub(r'\b(yesterday|today|tomorrow|next monday|last week|next week)\b', "[DATE]", out, flags=re.IGNORECASE)
    # replace long numeric ids
    out = re.sub(r'\b\d{5,}\b', "[ID]", out)

    # apply improved area masking
    out = mask_area(out)

    # extra fallback replacements for names/orgs
    out = re.sub(r'\b(' + r'|'.join(re.escape(tok) for tok in COMMON_PATIENT_TOKENS) + r')\b', '[PERSON]', out, flags=re.IGNORECASE)
    out = re.sub(r'\b(' + r'|'.join(re.escape(org) for org in COMMON_ORGS) + r')\b', '[HEALTHCARE_FACILITY]', out, flags=re.IGNORECASE)
    out = re.sub(r'\b(' + r'|'.join(re.escape(n) for n in COMMON_NAMES) + r')\b', "[PERSON]", out, flags=re.IGNORECASE)

    return out

# apply UPP to dataframe
df["perturbed"] = df["clean"].apply(apply_upp_masking_only)
print("\nApplied UPP masking to texts (perturbed column).")
# =======================
# Utility: Print clean vs perturbed text
# =======================
print("\n================ CLEAN vs PERTURBED ================\n")
for i in range(len(df)):
    print(f"--- Document {i} ---")
    print("CLEAN:     ", df.loc[i, "clean"])
    print("PERTURBED: ", df.loc[i, "perturbed"])
    print("\n")

# =======================
# Chunk 8: Embeddings & Index creation
# =======================
embed_model_name = "all-MiniLM-L6-v2"
embed_model = SentenceTransformer(embed_model_name, device=device)
print("Loaded embedder:", embed_model_name)

# document embeddings (perturbed)
doc_texts = df["perturbed"].tolist()
doc_embs = embed_model.encode(doc_texts, convert_to_numpy=True, show_progress_bar=False)

# node_texts from KG (fallback if none)
if len(node_texts) == 0:
    node_texts = ["[NO_NODE]"]
node_embs = embed_model.encode(node_texts, convert_to_numpy=True, show_progress_bar=False)

def normalize_np(X):
    norms = np.linalg.norm(X, axis=1, keepdims=True) + 1e-9
    return X / norms

doc_embs_n = normalize_np(doc_embs).astype("float32")
node_embs_n = normalize_np(node_embs).astype("float32")

# Create indexes (FAISS or sklearn)
if _HAS_FAISS:
    dim = doc_embs_n.shape[1]
    doc_index = faiss.IndexFlatIP(dim)
    doc_index.add(doc_embs_n)
    node_index = faiss.IndexFlatIP(node_embs_n.shape[1])
    node_index.add(node_embs_n)
    print("FAISS indexes created.")
else:
    doc_nn = NearestNeighbors(n_neighbors=5, metric="cosine").fit(doc_embs_n)
    node_nn = NearestNeighbors(n_neighbors=5, metric="cosine").fit(node_embs_n)
    print("Sklearn NN fallback indexes created.")

# =======================
# Chunk 9: Hybrid retrieval (no UPP on query)
# =======================
def hybrid_retrieve(query: str, top_k: int = 5, alpha: float = 0.6):
    q_emb = embed_model.encode([query], convert_to_numpy=True)
    qn = normalize_np(q_emb).astype("float32")

    doc_results = []
    node_results = []

    if _HAS_FAISS:
        Dd, Id = doc_index.search(qn, top_k)
        Dn, In = node_index.search(qn, top_k)
        for score, idx in zip(Dd[0], Id[0]):
            doc_results.append(("doc", int(idx), float(score)))
        for score, idx in zip(Dn[0], In[0]):
            node_results.append(("node", int(idx), float(score)))
    else:
        dists_doc, idxs_doc = doc_nn.kneighbors(qn, n_neighbors=top_k)
        dists_node, idxs_node = node_nn.kneighbors(qn, n_neighbors=top_k)
        for dist, idx in zip(dists_doc[0], idxs_doc[0]):
            sim = 1 - float(dist)
            doc_results.append(("doc", int(idx), sim))
        for dist, idx in zip(dists_node[0], idxs_node[0]):
            sim = 1 - float(dist)
            node_results.append(("node", int(idx), sim))

    merged = []
    for t, idx, s in doc_results:
        merged.append((t, idx, alpha * s))
    for t, idx, s in node_results:
        merged.append((t, idx, (1 - alpha) * s))
    merged_sorted = sorted(merged, key=lambda x: x[2], reverse=True)[:top_k]

    results = []
    for t, idx, score in merged_sorted:
        if t == "doc":
            text = doc_texts[idx]
        else:
            text = node_texts[idx]
        results.append({"type": t, "index": idx, "score": float(score), "text": text})
    return results

# =======================
# Chunk 10: Utility evaluation (BLEU & ROUGE-L)
# =======================
nltk.download("punkt", quiet=True)
smooth_fn = SmoothingFunction().method4
scorer = rouge_scorer.RougeScorer(["rougeL"], use_stemmer=True)

def eval_utility(ref: str, hyp: str) -> Tuple[float,float]:
    try:
        bleu = sentence_bleu([word_tokenize(ref.lower())], word_tokenize(hyp.lower()), smoothing_function=smooth_fn)
    except Exception:
        bleu = 0.0
    rouge = scorer.score(ref, hyp)["rougeL"].fmeasure
    return bleu, rouge

print("\nUtility Evaluation (Original vs Perturbed):")
for i in range(len(df)):
    ref = df.loc[i, "clean"]
    hyp = df.loc[i, "perturbed"]
    b, r = eval_utility(ref, hyp)
    print(f"Doc {i}: BLEU={b:.4f} | ROUGE-L={r:.4f}")

# =======================
# Chunk 11: Privacy leakage calculation & reporting
# =======================
def compute_privacy_leakage(original_texts: List[str], perturbed_texts: List[str]) -> Dict[str, Any]:
    sensitive_types = ["PERSON", "ORG", "DATE", "ID", "AGE", "AREA"]
    totals = {t:0 for t in sensitive_types}
    leaked_counts = {t:0 for t in sensitive_types}
    leaked_examples = {t:[] for t in sensitive_types}

    for orig, pert in zip(original_texts, perturbed_texts):
        ents = detect_entities_hf(orig)
        for e in ents:
            lbl = e.get("label","").upper()
            if any(k in lbl for k in ["PERSON","NAME","PATIENT"]):
                t = "PERSON"
            elif any(k in lbl for k in ["ORG","HOSPITAL","FACILITY"]):
                t = "ORG"
            elif any(k in lbl for k in ["DATE","TIME"]):
                t = "DATE"
            elif any(k in lbl for k in ["ID","NUMBER"]):
                t = "ID"
            elif "AGE" in lbl:
                t = "AGE"
            elif any(k in lbl for k in ["LOC","GPE","LOCATION","CITY","AREA"]):
                t = "AREA"
            else:
                t = None

            if t:
                totals[t] += 1
                if e["text"] in pert:
                    leaked_counts[t] += 1
                    leaked_examples[t].append({"text": e["text"], "orig_doc": orig})

    overall_total = sum(totals.values())
    overall_leaked = sum(leaked_counts.values())
    if overall_leaked > 0:
        leakage_value = overall_total / overall_leaked
    else:
        leakage_value = float("inf")

    leak_rates = {t: (leaked_counts[t] / totals[t] if totals[t]>0 else None) for t in sensitive_types}
    return {
        "per_type": {"total": totals, "leaked": leaked_counts, "leak_rate": leak_rates, "leaked_examples": leaked_examples},
        "overall": {"total_sensitive": overall_total, "leaked_sensitive": overall_leaked, "privacy_leakage_metric": leakage_value}
    }

# compute and print
original_texts = df["clean"].tolist()
perturbed_texts = df["perturbed"].tolist()
leakage_res = compute_privacy_leakage(original_texts, perturbed_texts)

print("\n======================================================================")
print("                   PRIVACY LEAKAGE ANALYSIS (GDPR-RELEVANT)")
print("======================================================================")
print("Overall Sensitive Entities Detected :", leakage_res["overall"]["total_sensitive"])
print("Leaked Entities (exact match)      :", leakage_res["overall"]["leaked_sensitive"])
val = leakage_res["overall"]["privacy_leakage_metric"]
if val == float("inf"):
    val_str = "inf"
else:
    val_str = f"{val:.2f}"
print("Privacy Leakage Metric (total/leaked):", val_str, "\n")

print("Per-Type Leakage Summary:")
print("--------------------------------------------------")
for typ in ["PERSON","ORG","DATE","ID","AGE","AREA"]:
    total = leakage_res["per_type"]["total"].get(typ,0)
    leaked = leakage_res["per_type"]["leaked"].get(typ,0)
    rate = leakage_res["per_type"]["leak_rate"].get(typ)
    rate_str = f"{rate*100:.1f}%" if rate is not None else "—"
    print(f"{typ:6s} | Total: {total:4d} | Leaked: {leaked:4d} | Leak Rate: {rate_str}")
print("----------------------------------------------------------------------")
print("\nSAMPLE LEAKED ENTITIES (for manual inspection & mitigation planning):\n")
for typ, examples in leakage_res["per_type"]["leaked_examples"].items():
    if examples:
        print(f"⚠️  HIGH-RISK TYPE: {typ}")
        for ex in examples[:5]:
            print(f"  • '{ex['text']}'")
            print("    Context:", ex["orig_doc"][:120])
        print()