# -*- coding: utf-8 -*-
"""proposed_with_squad.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q1ArPbCScKEMAySVUJmaoVvdstOBeRkw
"""

!pip install -q spacy sentence-transformers faiss-cpu transformers torch rouge-score nltk scikit-learn tqdm networkx
!python -m spacy download en_core_web_sm

from huggingface_hub import notebook_login
notebook_login()

# Chunk 1: Imports and dataset loading (uses 'input' column from the dataset)
import os
import re
import json
import random
import logging
from typing import List, Dict, Any, Tuple
import numpy as np
import pandas as pd

# Hugging Face datasets loader
from datasets import load_dataset

# NLP / Transformers
import torch
from transformers import pipeline, AutoTokenizer, AutoModelForTokenClassification, AutoModelForSequenceClassification

# Embeddings & indexes
from sentence_transformers import SentenceTransformer

# Graph
import networkx as nx

# Evaluation & text utils
import nltk
nltk.download("punkt")  # ensure tokenizer available
from nltk.tokenize import word_tokenize
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
from rouge_score import rouge_scorer

# Nearest neighbors fallback
from sklearn.neighbors import NearestNeighbors

# Try to import faiss; if missing, will use sklearn NN
try:
    import faiss
    _HAS_FAISS = True
except Exception:
    _HAS_FAISS = False

logging.basicConfig(level=logging.INFO)
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

# ----------------------------
# Load dataset (your snippet)
# ----------------------------
dataset_name = "rajpurkar/squad"
# limit split to a small portion for quick runs; change as needed
dataset = load_dataset(dataset_name, split="train[:1%]")

# convert to dataframe and select the 'input' column (fall back if missing)
df = pd.DataFrame(dataset)
if "context" not in df.columns:
    raise ValueError("Dataset does not contain an 'input' column. Available columns: " + ", ".join(df.columns))
# keep only the context column to avoid accidental downstream use of labels
df = df.rename(columns={"context": "input_raw"})

df.head(1)

# Chunk 1: Imports and dataset loading (uses 'input' column from the dataset)
import os
import re
import json
import random
import logging
from typing import List, Dict, Any, Tuple
import numpy as np
import pandas as pd

# Hugging Face datasets loader
from datasets import load_dataset

# NLP / Transformers
import torch
from transformers import pipeline, AutoTokenizer, AutoModelForTokenClassification, AutoModelForSequenceClassification

# Embeddings & indexes
from sentence_transformers import SentenceTransformer

# Graph
import networkx as nx

# Evaluation & text utils
import nltk
nltk.download("punkt")  # ensure tokenizer available
from nltk.tokenize import word_tokenize
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
from rouge_score import rouge_scorer

# Nearest neighbors fallback
from sklearn.neighbors import NearestNeighbors

# Try to import faiss; if missing, will use sklearn NN
try:
    import faiss
    _HAS_FAISS = True
except Exception:
    _HAS_FAISS = False

logging.basicConfig(level=logging.INFO)
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

# ----------------------------
# Load dataset (your snippet)
# ----------------------------
dataset_name = "rajpurkar/squad"
# limit split to a small portion for quick runs; change as needed
dataset = load_dataset(dataset_name, split="train[:1%]")

# convert to dataframe and select the 'input' column (fall back if missing)
df = pd.DataFrame(dataset)
if "context" not in df.columns:
    raise ValueError("Dataset does not contain an 'input' column. Available columns: " + ", ".join(df.columns))
# keep only the input column to avoid accidental downstream use of labels
df = df.rename(columns={"context": "input_raw"})
print(f"✅ Loaded {len(df)} samples from {dataset_name}")
df.head(1)

# Chunk 2: Preprocessing (cleaning + standardization)
import unicodedata

def clean_text(text: str) -> str:
    if not isinstance(text, str):
        return ""
    text = unicodedata.normalize("NFKC", text)
    text = re.sub(r"\s+", " ", text).strip()
    text = re.sub(r"<[^>]+>", " ", text)
    text = text.strip(" \t\n\r,.")
    return text

def standardize_dates(text: str) -> str:
    text = re.sub(r'\b(\d{4})[/-](\d{1,2})[/-](\d{1,2})\b', r'\1-\2-\3', text)
    text = re.sub(r'\b(\d{1,2})[/-](\d{1,2})[/-](\d{4})\b', r'\3-\1-\2', text)
    return text

df["clean"] = df["input_raw"].astype(str).apply(lambda x: standardize_dates(clean_text(x)))
print("Preprocessing done. Example (first row):")
print(df[["input_raw", "clean"]].iloc[0].to_dict())

# Chunk 3: Biomedical NER (pretrained) + fallback lexicons
NER_MODEL = "d4data/biomedical-ner-all"
FALLBACK_MODEL = "dslim/bert-base-NER"

try:
    ner = pipeline("ner", model=NER_MODEL, aggregation_strategy="simple", device=0 if device=="cuda" else -1)
    logging.info(f"Loaded NER model: {NER_MODEL}")
except Exception as e:
    logging.warning(f"Failed to load {NER_MODEL}: {e}. Falling back to {FALLBACK_MODEL}")
    ner = pipeline("ner", model=FALLBACK_MODEL, aggregation_strategy="simple", device=0 if device=="cuda" else -1)

def detect_entities_hf(text: str) -> List[Dict[str, Any]]:
    try:
        ents = ner(text)
    except Exception:
        ents = []
    out = []
    for e in ents:
        out.append({
            "text": e.get("word"),
            "label": e.get("entity_group", e.get("entity")),
            "start": int(e.get("start", 0)),
            "end": int(e.get("end", 0))
        })
    return out

# fallback lexicons (same as before)
COMMON_NAMES = [
    "john","jane","doe","smith","ali","ahmad","peterson","petreson","mike","maria","sara","ahmed"
]
COMMON_PATIENT_TOKENS = ["patient","baby","infant","child","newborn","childrens","kid","father","mother","son","daughter"]
COMMON_ORGS = [
    "mayo clinic","city health center","green valley surgery center","central hospital","quickmeds",
    "city health","regional hospital","pediatric ward"
]
COMMON_LOCATIONS = ["london","new york","california","islamabad","karachi"]

DISEASE_LEXICON = [
    "cancer","tumor","chest pain","headache","fever","dizziness","nausea",
    "vomiting","depression","anxiety","stomach pain","diabetes","hypertension",
    "migraine","asthma","flu","covid","malignant neoplasm","type 2 diabetes"
]

RE_ID_LONG = re.compile(r'\b\d{5,}\b')
RE_DATE_ISO = re.compile(r'\b(19|20)\d{2}[/-]\d{1,2}[/-]\d{1,2}\b', flags=re.IGNORECASE)
RE_RELATIVE_DATE = re.compile(r'\b(yesterday|today|tomorrow|next monday|last week|next week)\b', flags=re.IGNORECASE)

def detect_entities_fallback(text: str) -> List[Dict[str, Any]]:
    out = []
    text_low = text.lower()
    for name in (COMMON_NAMES + COMMON_PATIENT_TOKENS):
        for m in re.finditer(r'\b' + re.escape(name) + r'\b', text_low, flags=re.IGNORECASE):
            s, e = m.start(), m.end()
            out.append({"text": text[s:e], "label": "PERSON", "start": s, "end": e})
    for org in COMMON_ORGS:
        for m in re.finditer(re.escape(org), text_low, flags=re.IGNORECASE):
            s, e = m.start(), m.end()
            out.append({"text": text[s:e], "label": "ORG", "start": s, "end": e})
    for loc in COMMON_LOCATIONS:
        for m in re.finditer(r'\b' + re.escape(loc) + r'\b', text_low, flags=re.IGNORECASE):
            s, e = m.start(), m.end()
            out.append({"text": text[s:e], "label": "LOCATION", "start": s, "end": e})
    for d in DISEASE_LEXICON:
        for m in re.finditer(r'\b' + re.escape(d) + r'\b', text_low, flags=re.IGNORECASE):
            s, e = m.start(), m.end()
            out.append({"text": text[s:e], "label": "DISEASE", "start": s, "end": e})
    for m in RE_DATE_ISO.finditer(text):
        s, e = m.start(), m.end()
        out.append({"text": text[s:e], "label": "DATE", "start": s, "end": e})
    for m in RE_ID_LONG.finditer(text):
        s, e = m.start(), m.end()
        out.append({"text": text[s:e], "label": "ID", "start": s, "end": e})
    # dedupe by span+label
    seen = set()
    uniq = []
    for ent in sorted(out, key=lambda x: (x["start"], -x["end"])):
        key = (ent["start"], ent["end"], ent["label"])
        if key not in seen:
            seen.add(key)
            uniq.append(ent)
    return uniq

def detect_entities_final(text: str) -> List[Dict[str, Any]]:
    try:
        base = detect_entities_hf(text)
    except Exception:
        base = []
    fallback = detect_entities_fallback(text)
    covered_spans = set((e["start"], e["end"]) for e in base)
    merged = list(base)
    for f in fallback:
        if (f["start"], f["end"]) not in covered_spans:
            merged.append(f)
    merged_sorted = sorted(merged, key=lambda x: (x["start"], -x["end"]))
    final = []
    last_end = -1
    for e in merged_sorted:
        if e["start"] >= last_end:
            final.append(e)
            last_end = e["end"]
        else:
            if e["end"] > final[-1]["end"]:
                final[-1] = e
                last_end = e["end"]
    return final

# monkey patch
detect_entities_hf = detect_entities_final

# sanity check on first cleaned sample
print("NER demo on first cleaned sample:")
print(detect_entities_hf(df["clean"].iloc[0]))

# Chunk 4: Relation Extraction (transformer if available, else heuristic)
RE_MODEL = "PaDaS-Lab/privacy-policy-relation-extraction"
use_re_model = True
try:
    re_tokenizer = AutoTokenizer.from_pretrained(RE_MODEL)
    re_model = AutoModelForSequenceClassification.from_pretrained(RE_MODEL).to(device)
    if hasattr(re_model.config, "id2label"):
        re_id2label = re_model.config.id2label
    else:
        re_id2label = {i: str(i) for i in range(re_model.config.num_labels)}
    logging.info(f"Loaded RE model: {RE_MODEL}")
except Exception as e:
    logging.warning(f"RE model load failed ({e}). Falling back to heuristic relation extraction.")
    use_re_model = False
    re_tokenizer = None
    re_model = None
    re_id2label = {}

def extract_relations_transformer(text: str, entities: List[Dict[str, Any]]) -> List[Tuple[str,str,str]]:
    rels = []
    if not use_re_model or len(entities) < 2:
        return rels
    for e1 in entities:
        for e2 in entities:
            if e1 == e2:
                continue
            marked = (text[:e1["start"]] + "[E1]" + e1["text"] + "[/E1]" + text[e1["end"]:e2["start"]] +
                     "[E2]" + e2["text"] + "[/E2]" + text[e2["end"]:])
            inputs = re_tokenizer(marked, truncation=True, max_length=256, return_tensors="pt").to(device)
            with torch.no_grad():
                out = re_model(**inputs)
                pred = torch.argmax(out.logits, dim=1).item()
                label = re_id2label.get(pred, str(pred))
                if label and label.lower() not in ("no_relation","0"):
                    rels.append((e1["text"], label, e2["text"]))
    return rels

def extract_relations_heuristic(text: str, entities: List[Dict[str, Any]]) -> List[Tuple[str,str,str]]:
    rels = []
    s_text = text.lower()
    for e1 in entities:
        for e2 in entities:
            if e1 == e2:
                continue
            if "prescrib" in s_text or "given" in s_text or "prescribed" in s_text or "mg" in s_text:
                rels.append((e1["text"], "MEDICATED_WITH", e2["text"]))
            elif "visit" in s_text or "visited" in s_text or "appointment" in s_text:
                rels.append((e1["text"], "VISITED", e2["text"]))
            elif "diagnos" in s_text or "diagnosed" in s_text:
                rels.append((e1["text"], "DIAGNOSED_WITH", e2["text"]))
    rels = list(set(rels))
    return rels

def extract_relations(text: str, entities: List[Dict[str, Any]]) -> List[Tuple[str,str,str]]:
    rels = extract_relations_transformer(text, entities)
    if not rels:
        rels = extract_relations_heuristic(text, entities)
    return rels

# Chunk 5: Build Knowledge Graph from cleaned texts; collect node map & relations
def build_kg_and_maps(texts: List[str]):
    G = nx.Graph()
    node_texts = []  # list of node texts (original)
    node_map = {}    # node_id -> {"text":..., "label":..., "doc_id":...}
    relations = []   # list of (node_id_h, relation_label, node_id_t, doc_id)

    for i, text in enumerate(texts):
        ents = detect_entities_hf(text)
        # add nodes
        for e in ents:
            node_id = f"{i}:{e['text']}:{e['label']}"
            if node_id not in node_map:
                node_map[node_id] = {"text": e["text"], "label": e["label"], "doc_id": i}
                node_texts.append(e["text"])
                G.add_node(node_id, label=e['label'], text=e['text'], doc_id=i)
        # extract relations for this doc
        rels = extract_relations(text, ents)
        for h, r, t in rels:
            # find node ids within this doc for h and t (prefer exact text match)
            possible_h = [nid for nid,meta in node_map.items() if meta["text"]==h and meta["doc_id"]==i]
            possible_t = [nid for nid,meta in node_map.items() if meta["text"]==t and meta["doc_id"]==i]
            if possible_h and possible_t:
                node_h = possible_h[0]
                node_t = possible_t[0]
                relations.append((node_h, r, node_t, i))
                G.add_edge(node_h, node_t, relation=r, doc_id=i)
    return G, node_map, relations

texts_for_kg = df["clean"].tolist()
KG, node_map, relations = build_kg_and_maps(texts_for_kg)
print("KG nodes:", KG.number_of_nodes(), "edges:", KG.number_of_edges())
# sample
list(node_map.items())[:5], relations[:5]

# Chunk 6: AI-UPP applied ONLY on node texts (not whole dataset)
# We'll reuse your earlier UPP functions but call them on the node text strings.

# (Re-declare small helpers required by UPP if not already in scope)
dosage_pattern = re.compile(
    r"\b\d+\s?(?:mg|mcg|g|gram|grams|kg|ml|mL|L|units|IU|tablet|tablets|capsule|capsules|tab|tabs|pills?|dose|doses|tbsp|mls?)\b",
    flags=re.IGNORECASE
)
RE_DATE_ISO = re.compile(r'\b(19|20)\d{2}[/-]\d{1,2}[/-]\d{1,2}\b', flags=re.IGNORECASE)
RE_RELATIVE_DATE = re.compile(r'\b(yesterday|today|tomorrow|next monday|last week|next week)\b', flags=re.IGNORECASE)
RE_ID_LONG = re.compile(r'\b\d{5,}\b')

def coarsen_date_to_year(date_text: str) -> str:
    m = re.search(r'\b(19|20)\d{2}\b', date_text)
    if m:
        return f"[DATE:{m.group(0)}]"
    return "[DATE]"

# dp noise function (same as you had)
def dp_age_noise(age_value: int, epsilon: float = 1.0) -> int:
    try:
        a = int(age_value)
    except Exception:
        return age_value
    noise = np.random.laplace(0, 1.0 / max(epsilon, 1e-6))
    noisy = int(round(a + noise))
    if noisy < 0 or noisy > 120:
        noisy = max(0, min(120, a + int(round(np.sign(noise) * min(10, abs(noise))))))
    return noisy

def mask_or_coarsen_age(span_text: str, dp_epsilon: float = 1.0, mode: str = "dp"):
    if dosage_pattern.search(span_text):
        return span_text
    m = re.search(r'(\d{1,3})', span_text)
    if not m:
        return "[AGE]"
    val = int(m.group(1))
    if mode == "mask":
        return "[AGE]"
    if mode == "range":
        r = 5
        low = max(0, val - r)
        high = val + r
        return f"[AGE:{low}-{high}]"
    noisy = dp_age_noise(val, epsilon=dp_epsilon)
    return f"[AGE:{noisy}]"

def mask_area_text(text: str) -> str:
    facility_pattern = re.compile(
        r"\b([A-Z][a-z]+(?:\s+[A-Z][a-z]+){0,3}\s+(Hospital|Clinic|Center|Surgery|Care|Medical|Health))\b",
        flags=re.IGNORECASE
    )
    text = facility_pattern.sub("[AREA]", text)
    area_terms = ["Hospital", "Clinic", "Center", "Surgery", "Medical Center", "Health Center", "Care Center"]
    for term in area_terms:
        text = re.sub(rf"\b{re.escape(term)}\b", "[AREA]", text, flags=re.IGNORECASE)
    return text

# Reuse your entity-aware masking function but apply to short node strings.
# It will run NER/fallback again on that small text (ok for node-level masking).
def apply_upp_to_span(span_text: str, dp_age: bool = True, dp_age_epsilon: float = 1.0) -> str:
    # detect entities in this small span (uses detect_entities_hf with fallback)
    ents = detect_entities_hf(span_text)
    out = span_text
    for ent in sorted(ents, key=lambda x: x["start"], reverse=True):
        lbl = ent.get("label", "").upper()
        s, e = ent["start"], ent["end"]
        span = ent["text"]
        if any(k in lbl for k in ["PERSON", "PATIENT", "NAME"]):
            out = out[:s] + "[PERSON]" + out[e:]
        elif any(k in lbl for k in ["ORG", "HOSPITAL", "FACILITY", "ORGANIZATION"]):
            out = out[:s] + "[HEALTHCARE_FACILITY]" + out[e:]
        elif any(k in lbl for k in ["LOC", "GPE", "LOCATION", "CITY", "AREA", "COUNTRY"]):
            out = out[:s] + "[AREA]" + out[e:]
        elif "DATE" in lbl or "TIME" in lbl:
            coarse = coarsen_date_to_year(span)
            out = out[:s] + coarse + out[e:]
        elif any(k in lbl for k in ["ID", "NUMBER"]) and len(re.sub(r'\s', '', span)) >= 5:
            out = out[:s] + "[ID]" + out[e:]
        elif "AGE" in lbl:
            if dp_age:
                replaced = mask_or_coarsen_age(span, dp_epsilon=dp_age_epsilon, mode="dp")
            else:
                replaced = mask_or_coarsen_age(span, dp_epsilon=dp_age_epsilon, mode="range")
            out = out[:s] + replaced + out[e:]
        else:
            pass

    # regex fallbacks for node-level
    out = re.sub(r'\b(John|Jane|Doe|Smith|Ali|Patient|Baby|child|father|mother|son|daughter)\b', '[PERSON]', out, flags=re.IGNORECASE)
    out = re.sub(r'\b(Mayo\s+Clinic|City\s+Health\s+Center|Green\s+Valley\s+Surgery\s+Center|Central\s+Hospital|QuickMeds)\b',
                 '[HEALTHCARE_FACILITY]', out, flags=re.IGNORECASE)
    out = re.sub(r'\b(London|New York|California|Islamabad|Karachi)\b', '[AREA]', out, flags=re.IGNORECASE)
    out = re.sub(RE_DATE_ISO, lambda m: coarsen_date_to_year(m.group(0)), out)
    out = re.sub(RE_RELATIVE_DATE, '[DATE]', out)
    out = re.sub(RE_ID_LONG, '[ID]', out)
    out = mask_area_text(out)
    return out

# Apply UPP only to node_map entries (create masked_node_map)
masked_node_map = {}
for nid, meta in node_map.items():
    orig_text = meta["text"]
    masked = apply_upp_to_span(orig_text, dp_age=True, dp_age_epsilon=1.0)
    masked_node_map[nid] = {**meta, "masked_text": masked}

# Example: show 5 masked nodes
list(masked_node_map.items())[:5]

# Chunk 7: Create relation text strings using masked node texts, then create embeddings and separate FAISS indexes

# Prepare node_texts_masked and relation_texts_masked
node_ids = list(masked_node_map.keys())
node_texts_masked = [masked_node_map[nid]["masked_text"] for nid in node_ids]

# Relation representation: combine masked head + relation label + masked tail
relation_entries = []  # list of (rel_id, rel_text)
for i, (h, r, t, doc_id) in enumerate(relations):
    # ensure nodes exist in masked map
    mh = masked_node_map.get(h, {"masked_text": "[UNKNOWN]"})["masked_text"]
    mt = masked_node_map.get(t, {"masked_text": "[UNKNOWN]"})["masked_text"]
    rel_text = f"{mh} {r} {mt}"
    rel_id = f"rel:{i}:{h}->{t}"
    relation_entries.append((rel_id, rel_text))

relation_ids = [r[0] for r in relation_entries]
relation_texts_masked = [r[1] for r in relation_entries]


# Load embedder
embed_model_name = "all-MiniLM-L6-v2"
embed_model = SentenceTransformer(embed_model_name, device=device)
print("Loaded embedder:", embed_model_name)

# Compute embeddings
if len(node_texts_masked) == 0:
    node_texts_masked = ["[NO_NODE]"]
if len(relation_texts_masked) == 0:
    relation_texts_masked = ["[NO_REL]"]

node_embs = embed_model.encode(node_texts_masked, convert_to_numpy=True, show_progress_bar=True)
rel_embs = embed_model.encode(relation_texts_masked, convert_to_numpy=True, show_progress_bar=True)

# normalize
def normalize_np(X):
    norms = np.linalg.norm(X, axis=1, keepdims=True) + 1e-9
    return X / norms

node_embs_n = normalize_np(node_embs).astype("float32")
rel_embs_n = normalize_np(rel_embs).astype("float32")

# create FAISS indexes (two separate indexes)
if _HAS_FAISS:
    node_dim = node_embs_n.shape[1]
    rel_dim = rel_embs_n.shape[1]
    node_index = faiss.IndexFlatIP(node_dim)
    rel_index = faiss.IndexFlatIP(rel_dim)
    node_index.add(node_embs_n)
    rel_index.add(rel_embs_n)
    print("FAISS indexes created for nodes and relations.")
else:
    node_nn = NearestNeighbors(n_neighbors=10, metric="cosine").fit(node_embs_n)
    rel_nn = NearestNeighbors(n_neighbors=10, metric="cosine").fit(rel_embs_n)
    print("Sklearn fallback indexes created for nodes and relations.")

# Chunk 8: Hybrid retriever that searches both node_index and rel_index
def kg_hybrid_retrieve(query: str, top_k: int = 5, alpha: float = 0.6):
    """
    alpha: weight for node score; (1-alpha) weight for relation score.
    Returns combined top_k results with fields: {'type': 'node'|'relation', 'id': id, 'score': float, 'text': text}
    """
    q_emb = embed_model.encode([query], convert_to_numpy=True)
    qn = normalize_np(q_emb).astype("float32")

    node_results = []
    rel_results = []

    if _HAS_FAISS:
        Dn, In = node_index.search(qn, top_k)
        Dr, Ir = rel_index.search(qn, top_k)
        for score, idx in zip(Dn[0], In[0]):
            node_results.append(("node", int(idx), float(score)))
        for score, idx in zip(Dr[0], Ir[0]):
            rel_results.append(("relation", int(idx), float(score)))
    else:
        dists_node, idxs_node = node_nn.kneighbors(qn, n_neighbors=top_k)
        dists_rel, idxs_rel = rel_nn.kneighbors(qn, n_neighbors=top_k)
        for dist, idx in zip(dists_node[0], idxs_node[0]):
            sim = 1 - float(dist)
            node_results.append(("node", int(idx), sim))
        for dist, idx in zip(dists_rel[0], idxs_rel[0]):
            sim = 1 - float(dist)
            rel_results.append(("relation", int(idx), sim))

    merged = []
    for t, idx, s in node_results:
        merged.append((t, idx, alpha * s))
    for t, idx, s in rel_results:
        merged.append((t, idx, (1 - alpha) * s))
    merged_sorted = sorted(merged, key=lambda x: x[2], reverse=True)[:top_k]

    results = []
    for t, idx, score in merged_sorted:
        if t == "node":
            text = node_texts_masked[idx]
            id_out = node_ids[idx]
        else:
            text = relation_texts_masked[idx]
            id_out = relation_ids[idx]
        results.append({"type": t, "id": id_out, "score": float(score), "text": text})
    return results

# Demo queries -> will retrieve masked node/relation texts (so privacy-preserving)
queries = [
    "What is the architectural character of the school?",
    "What statue is atop the Main Building's dome?",
    "What statue is in front of the Main Building?",
    "What is next to the Main Building?",
    "What is behind the basilica?",
    "What is special about the Grotto?",
    "What statue is at the end of the main drive?"
]

for q in queries:
    print("\nQuery:", q)
    hits = kg_hybrid_retrieve(q, top_k=5, alpha=0.7)

    for h in hits:
        print("\n--- Result ---")
        print("Type: answer")
        print("Masked Text:", h["text"])

# -----------------------------
# CHUNK A: BLEU SCORE EVALUATION
# -----------------------------

from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
from nltk.tokenize import word_tokenize
import numpy as np

smooth_fn = SmoothingFunction().method4
bleu_scores = []

for i, nid in enumerate(node_ids):
    orig = node_map[nid]["text"]
    hyp = node_texts_masked[i]

    try:
        bleu = sentence_bleu(
            [word_tokenize(orig.lower())],
            word_tokenize(hyp.lower()),
            smoothing_function=smooth_fn
        )
    except Exception:
        bleu = 0.0

    bleu_scores.append(bleu)

avg_bleu = float(np.mean(bleu_scores)) if bleu_scores else 0.0

print("\n=== NODE-LEVEL BLEU UTILITY ===")
print(f"Average BLEU: {avg_bleu:.4f}")

# -----------------------------
# CHUNK B: ROUGE-L SCORE EVALUATION
# -----------------------------

from rouge_score import rouge_scorer
import numpy as np

scorer = rouge_scorer.RougeScorer(["rougeL"], use_stemmer=True)
rougeL_scores = []

for i, nid in enumerate(node_ids):
    orig = node_map[nid]["text"]
    hyp = node_texts_masked[i]

    try:
        rougeL = scorer.score(orig, hyp)["rougeL"].fmeasure
    except Exception:
        rougeL = 0.0

    rougeL_scores.append(rougeL)

avg_rougeL = float(np.mean(rougeL_scores)) if rougeL_scores else 0.0

print("\n=== NODE-LEVEL ROUGE-L UTILITY ===")
print(f"Average ROUGE-L: {avg_rougeL:.4f}")

# ======================= CHUNK X: ENTITY LEAKAGE RATE =======================

import re

# patterns that should NEVER appear in masked nodes
ARCHITECTURE_WORDS = [
    "Main Building", "Basilica of the Sacred Heart", "Grotto",
    "Gold Dome", "Virgin Mary"
]

DATE_PATTERN = re.compile(r'\b(19|20)\d{2}[/-]\d{1,2}[/-]\d{1,2}\b', flags=re.IGNORECASE)
ID_PATTERN = re.compile(r'\b\d{5,}\b')

def is_leaky(original, masked):
    """Return True if masked still leaks sensitive info."""
    o = original.lower()
    m = masked.lower()

    # architecture/entity leak
    for w in ARCHITECTURE_WORDS:
        if w.lower() in m and w.lower() in o:
            return True

    # explicit date leak
    if DATE_PATTERN.search(m):
        return True

    # ID leak
    if ID_PATTERN.search(m):
        return True

    return False

# Example usage: calculate leakage
total_nodes = len(node_ids)
leaky_count = 0
examples = []

for i, nid in enumerate(node_ids):
    orig = node_map[nid]["text"]
    masked = masked_node_map[nid]["masked_text"]

    if is_leaky(orig, masked):
        leaky_count += 1
        if len(examples) < 10:
            examples.append((orig, masked))

leakage_rate = (leaky_count / total_nodes) if total_nodes > 0 else 0

print("\n=== ENTITY LEAKAGE RATE ===")
print(f"Entity Leakage rate: {leakage_rate*100:.2f}%")

print("\nExamples of leaked nodes:")
for o, m in examples:
    print(f"  ORIG: {o}  -->  MASKED: {m}")

"""Second"""

