# -*- coding: utf-8 -*-
"""without_KG_HealthCareMagic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oZokJRofeb-KtyQ-qVm0l6QKZ0jKl3GI
"""

from huggingface_hub import notebook_login
notebook_login()

!pip install -q spacy sentence-transformers faiss-cpu transformers torch rouge-score nltk scikit-learn tqdm networkx
!python -m spacy download en_core_web_sm

# -----------------------------------------
# CHUNK 1: Imports
# -----------------------------------------
import os
import re
import json
import logging
import numpy as np
import pandas as pd
import unicodedata

from datasets import load_dataset
import torch

# NER / Transformers
from transformers import pipeline, AutoTokenizer, AutoModelForTokenClassification

# Embeddings
from sentence_transformers import SentenceTransformer

# Classical retrieval
from sklearn.neighbors import NearestNeighbors

# Tokenization + scoring
import nltk
from nltk.tokenize import word_tokenize
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
from rouge_score import rouge_scorer

# Vector Index
try:
    import faiss
    _HAS_FAISS = True
except:
    _HAS_FAISS = False

logging.basicConfig(level=logging.INFO)
device = "cuda" if torch.cuda.is_available() else "cpu"

import argparse
import json
import os
import re
import math
from dataclasses import dataclass
from typing import List, Dict, Tuple, Any

import numpy as np
import pandas as pd

# -----------------------------------------
# CHUNK 2: Load the Dataset
# -----------------------------------------
dataset = load_dataset("wangrongsheng/HealthCareMagic-100k-en", split="train[:1%]")

df = pd.DataFrame(dataset)

# Ensure expected column exists
if "input" not in df.columns:
    raise ValueError("Dataset missing 'input' column")

# rename to standard name
df = df.rename(columns={"input": "input_raw"})

# -----------------------------------------
# CHUNK 3: Clean Text
# -----------------------------------------
def clean_text(text: str) -> str:
    if not isinstance(text, str):
        return ""

    # normalize weird unicode
    text = unicodedata.normalize("NFKC", text)

    # remove HTML tags
    text = re.sub(r"<[^>]+>", " ", text)

    # collapse multiple spaces
    text = re.sub(r"\s+", " ", text)

    return text.strip(" \t\n\r,.")  # quick trim

df["clean"] = df["input_raw"].apply(clean_text)

print("✨ Cleaning done.")
df.head()

SAMPLE_N = 3   # how many sample rows to print and test
TOP_K = 5      # how many retrieval results to print per query
DP_SIGMA = 0.15  # gaussian noise sigma for DP on embeddings (0 -> no DP)
ALPHA = 0.5    # hybrid weighting: 0=dense-only, 1=sparse-only (we use dense* (1-alpha) + bm25*alpha below)

# -----------------------------------------
# CHUNK 4: Load NER Model (Bio-Medical)
# -----------------------------------------
NER_MODEL = "d4data/biomedical-ner-all"

ner_pipe = pipeline(
    "token-classification",
    model=NER_MODEL,
    aggregation_strategy="simple",
    device=0 if torch.cuda.is_available() else -1
)

print("🤖 NER model loaded.")

# -----------------------------------------
# CHUNK 5: Extract Entities
# -----------------------------------------
def extract_entities(text):
    out = ner_pipe(text)
    ents = []
    for e in out:
        ents.append({
            "text": e["word"],
            "start": e["start"],
            "end": e["end"],
            "label": e["entity_group"]
        })
    return ents

df["entities"] = df["clean"].apply(extract_entities)
print("🩺 Extracted entities for dataset.")

# -----------------------------------------
# CHUNK 6: Mask Entities with Labels
# -----------------------------------------
import re

# regex patterns for PII with labels
PII_PATTERNS = {
    r"\b\d{4,}\b": "[ID]",
    r"\b\d{1,2}[-/.]\d{1,2}[-/.]\d{2,4}\b": "[DATE]",
    r"\b\d{3}[-.]\d{3}[-.]\d{4}\b": "[PHONE]",
    r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}": "[EMAIL]"
}

def mask_with_labels(text, entities):
    if not text:
        return text

    # mask NER spans with their labels
    spans = sorted([(max(0, e["start"]), min(len(text), e["end"]), e["label"]) for e in entities], key=lambda x: x[0])
    masked = []
    last = 0
    for start, end, label in spans:
        masked.append(text[last:start])
        masked.append(f"[{label}]")  # use the label as mask
        last = end
    masked.append(text[last:])
    masked_text = "".join(masked)

    # mask regex PII with type
    for pattern, label in PII_PATTERNS.items():
        masked_text = re.sub(pattern, label, masked_text)

    return masked_text

# apply
df["masked"] = df.apply(lambda row: mask_with_labels(row["clean"], row["entities"]), axis=1)

# --- leakage detection ---
def compute_leaks_with_labels(row):
    clean = row["clean"]
    masked = row["masked"]
    ents = row["entities"]
    leaked = []

    for e in ents:
        span = clean[e["start"]:e["end"]].strip()
        if span and span in masked:
            leaked.append((span, e["label"]))
    return leaked

df["mask_leaks"] = df.apply(compute_leaks_with_labels, axis=1)

# mask leakage rate
total_entities = sum(len(x) for x in df["entities"])
total_mask_leaks = sum(len(x) for x in df["mask_leaks"])
mask_leakage_rate = (total_mask_leaks / total_entities) if total_entities > 0 else 0.0

#print(f"🔒 Mask Leakage Rate with Labels: {mask_leakage_rate:.4f} ({total_mask_leaks} leaked / {total_entities} total)")

# sample
for i in range(3):
    print(f"\nOriginal: {df['clean'].iloc[i]}")
    print(f"Masked  : {df['masked'].iloc[i]}")

# -----------------------------------------
# CHUNK 7: Simplified Coarsening + Leakage
# -----------------------------------------
import re

# Days of the week for labeling
DAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]

def coarsen_simple(text):
    if not text:
        return text

    # 1️⃣ Replace explicit dates (YYYY-MM-DD, DD/MM/YYYY, etc.)
    text = re.sub(r"\b\d{4}[-/.]\d{2}[-/.]\d{2}\b", "[DATE]", text)
    text = re.sub(r"\b\d{1,2}[-/]\d{1,2}[-/]\d{2,4}\b", "[DATE]", text)

    # 2️⃣ Replace day names
    for day in DAYS:
        text = re.sub(rf"\b{day}\b", "[DAY]", text, flags=re.IGNORECASE)

    # 3️⃣ Replace age patterns
    text = re.sub(r"\bage\s*\d{1,3}\b", "[AGE]", text, flags=re.IGNORECASE)
    text = re.sub(r"\b\d{1,3}[- ]?year[- ]?old\b", "[AGE]", text, flags=re.IGNORECASE)

    return text

# Apply coarsening
df["coarsened"] = df["masked"].apply(coarsen_simple)

# Leakage check after coarsening
def compute_coarse_leaks(row):
    clean = row["clean"]
    coarse = row["coarsened"]
    ents = row["entities"]
    leaked = []
    for e in ents:
        span = clean[e["start"]:e["end"]].strip()
        if span and span in coarse:
            leaked.append(span)
    return leaked

df["coarse_leaks"] = df.apply(compute_coarse_leaks, axis=1)

# Coarsening leakage rate
total_coarse_leaks = sum(len(x) for x in df["coarse_leaks"])
coarsening_leakage_rate = (total_coarse_leaks / total_entities) if total_entities > 0 else 0.0

#print(f"🔒 Simplified Coarsening Leakage Rate: {coarsening_leakage_rate:.4f} ({total_coarse_leaks} leaked / {total_entities} total)")

# Sample sentences to check if coarsening works
sample_n = 2
print(f"\n📄 Showing {sample_n} sample sentences after coarsening:")
for i in range(sample_n):
    print(f"\nOriginal : {df['clean'].iloc[i]}")
    print(f"Masked   : {df['masked'].iloc[i]}")
    print(f"Coarsened: {df['coarsened'].iloc[i]}")

# -----------------------------------------
# CHUNK 8: Embedding Generation + DP
# -----------------------------------------
EMBED_MODEL = "sentence-transformers/all-mpnet-base-v2"
embedder = SentenceTransformer(EMBED_MODEL)

# encode to numpy array
texts = df["coarsened"].astype(str).tolist()
emb_matrix = embedder.encode(texts, convert_to_numpy=True, show_progress_bar=True)

# store embeddings per row as list (so pandas column holds one vector per cell)
df["embedding"] = [v for v in emb_matrix]

# apply gaussian DP noise (on the embedding vectors)
def add_gaussian_noise_matrix(mat, sigma=0.0):
    if sigma <= 0.0:
        return mat
    noise = np.random.normal(0, sigma, size=mat.shape)
    return mat + noise

emb_matrix_dp = add_gaussian_noise_matrix(emb_matrix, sigma=DP_SIGMA)

# store DP embeddings per row
df["embedding_dp"] = [v for v in emb_matrix_dp]

# small DP-summary per sample (norm & first 5 dims)
def dp_summary(vec, vec_dp):
    orig_norm = float(np.linalg.norm(vec))
    dp_norm = float(np.linalg.norm(vec_dp))
    first_dims = vec_dp[:5].tolist()
    return {"orig_norm": orig_norm, "dp_norm": dp_norm, "dp_first5": first_dims}

df["dp_summary"] = [dp_summary(o, d) for o, d in zip(df["embedding"], df["embedding_dp"])]

print("🧠 Embeddings + DP applied, sample DP summaries:")
print(df[["coarsened", "dp_summary"]].head(SAMPLE_N).to_dict(orient="records"))

!pip install rank-bm25

# -----------------------------------------
# CHUNK 9: Build FAISS index (or fallback to sklearn) + BM25
# -----------------------------------------
emb_matrix_for_index = np.vstack(df["embedding_dp"].values).astype("float32")
# normalize to unit vectors for cosine similarity via inner product
norms = np.linalg.norm(emb_matrix_for_index, axis=1, keepdims=True)
norms[norms == 0] = 1.0
emb_normed = emb_matrix_for_index / norms

if _HAS_FAISS:
    index = faiss.IndexFlatIP(emb_normed.shape[1])  # inner product on normalized vectors = cosine
    index.add(emb_normed)
    print("📚 FAISS index built with vectors.")
else:
    # fallback: use sklearn NearestNeighbors on normalized vectors
    from sklearn.neighbors import NearestNeighbors
    nn = NearestNeighbors(n_neighbors=TOP_K, metric="cosine").fit(emb_normed)
    print("⚠️ FAISS not available — using sklearn NearestNeighbors fallback.")

# BM25
from rank_bm25 import BM25Okapi
tokenized = [t.split() for t in df["coarsened"].astype(str).tolist()]
bm25 = BM25Okapi(tokenized)
print("🔎 BM25 index built.")

# -----------------------------------------
# CHUNK 10: Hybrid retrieval (dense + sparse)
# -----------------------------------------
def dense_search_faiss(query_vec, top_k=TOP_K):
    # returns (indices, scores)
    qv = query_vec.astype("float32")
    qn = qv / (np.linalg.norm(qv) + 1e-9)
    if _HAS_FAISS:
        D, I = index.search(qn.reshape(1, -1), top_k)
        return I[0].tolist(), D[0].tolist()
    else:
        # sklearn NearestNeighbors returns distances; convert to similarity-like score (1 - dist)
        dists, idxs = nn.kneighbors(qn.reshape(1, -1), n_neighbors=top_k)
        sims = (1 - dists[0]).tolist()
        return idxs[0].tolist(), sims

def hybrid_search(query, top_k=TOP_K, alpha=ALPHA):
    # BM25 scores
    q_tokens = query.split()
    bm25_scores = bm25.get_scores(q_tokens)  # length = len(df)
    if bm25_scores.max() == 0:
        bm25_norm = bm25_scores
    else:
        bm25_norm = bm25_scores / (bm25_scores.max() + 1e-9)
    # Dense scores
    q_emb = embedder.encode([query], convert_to_numpy=True)[0]
    # search dense
    idxs, dense_scores = dense_search_faiss(q_emb, top_k=len(df))
    dense_full = np.zeros(len(df))
    dense_full[idxs] = dense_scores
    if dense_full.max() == 0:
        dense_norm = dense_full
    else:
        dense_norm = dense_full / (dense_full.max() + 1e-9)
    # combine: final_score = (1-alpha) * dense + alpha * bm25  (you can swap semantics easily)
    final = (1 - alpha) * dense_norm + alpha * bm25_norm
    top_idx = np.argsort(-final)[:top_k]
    top_scores = final[top_idx]
    return top_idx.tolist(), top_scores.tolist()

def print_retrieval_results(query, top_k=TOP_K):
    top_idx, scores = hybrid_search(query, top_k=top_k, alpha=ALPHA)
    print("\n🔍 Query:", query)
    for rank, (i, s) in enumerate(zip(top_idx, scores), start=1):
        print(f"\nRank {rank} (idx {i}) — score {s:.4f}")
        print("CLEAN:", df.loc[i, "clean"])
        print("MASKED:", df.loc[i, "masked"])
        print("COARSENED:", df.loc[i, "coarsened"])
    return top_idx, scores

print("🧲 Hybrid retrieval function ready.")

import nltk
nltk.download('punkt')
import nltk
nltk.download('punkt_tab')

# ---------------------------
# HYBRID RETRIEVER (Masked Output)
# ---------------------------
def dense_search_faiss(query_vec, top_k=TOP_K):
    qv = query_vec.astype("float32")
    qn = qv / (np.linalg.norm(qv) + 1e-9)
    if _HAS_FAISS:
        D, I = index.search(qn.reshape(1, -1), top_k)
        return I[0].tolist(), D[0].tolist()
    else:
        dists, idxs = nn.kneighbors(qn.reshape(1, -1), n_neighbors=top_k)
        sims = (1 - dists[0]).tolist()
        return idxs[0].tolist(), sims

def hybrid_search(query, top_k=TOP_K, alpha=ALPHA):
    # BM25 scores
    q_tokens = query.split()
    bm25_scores = bm25.get_scores(q_tokens)
    bm25_norm = bm25_scores / (bm25_scores.max() + 1e-9) if bm25_scores.max() != 0 else bm25_scores

    # Dense scores
    q_emb = embedder.encode([query], convert_to_numpy=True)[0]
    idxs, dense_scores = dense_search_faiss(q_emb, top_k=len(df))
    dense_full = np.zeros(len(df))
    dense_full[idxs] = dense_scores
    dense_norm = dense_full / (dense_full.max() + 1e-9) if dense_full.max() != 0 else dense_full

    # Combine scores: final = (1-alpha) * dense + alpha * bm25
    final = (1 - alpha) * dense_norm + alpha * bm25_norm
    top_idx = np.argsort(-final)[:top_k]
    top_scores = final[top_idx]
    return top_idx.tolist(), top_scores.tolist()

def print_masked_retriever(query, top_k=TOP_K):
    top_idx, scores = hybrid_search(query, top_k=top_k, alpha=ALPHA)
    print("\n🔍 Query:", query)
    for rank, (i, s) in enumerate(zip(top_idx, scores), start=1):
        # Use masked/coarsened version for output
        output_text = df.loc[i, "masked"]
        print(f"\nAnswer {rank}: {output_text}  (score: {s:.4f})")
    return top_idx, scores

# ---------------------------
# EXAMPLES
# ---------------------------
queries = [
    "What medication is suggested for chest pain?",
    "Which clinics were visited for vomiting and fever?"
]

for q in queries:
    print_masked_retriever(q)

# ---------------------------
# HYBRID RETRIEVER (Masked Output)
# ---------------------------
def dense_search_faiss(query_vec, top_k=TOP_K):
    qv = query_vec.astype("float32")
    qn = qv / (np.linalg.norm(qv) + 1e-9)
    if _HAS_FAISS:
        D, I = index.search(qn.reshape(1, -1), top_k)
        return I[0].tolist(), D[0].tolist()
    else:
        dists, idxs = nn.kneighbors(qn.reshape(1, -1), n_neighbors=top_k)
        sims = (1 - dists[0]).tolist()
        return idxs[0].tolist(), sims

def hybrid_search(query, top_k=TOP_K, alpha=ALPHA):
    # BM25 scores
    q_tokens = query.split()
    bm25_scores = bm25.get_scores(q_tokens)
    bm25_norm = bm25_scores / (bm25_scores.max() + 1e-9) if bm25_scores.max() != 0 else bm25_scores

    # Dense scores
    q_emb = embedder.encode([query], convert_to_numpy=True)[0]
    idxs, dense_scores = dense_search_faiss(q_emb, top_k=len(df))
    dense_full = np.zeros(len(df))
    dense_full[idxs] = dense_scores
    dense_norm = dense_full / (dense_full.max() + 1e-9) if dense_full.max() != 0 else dense_full

    # Combine scores: final = (1-alpha) * dense + alpha * bm25
    final = (1 - alpha) * dense_norm + alpha * bm25_norm
    top_idx = np.argsort(-final)[:top_k]
    top_scores = final[top_idx]
    return top_idx.tolist(), top_scores.tolist()

def print_masked_retriever(query, top_k=TOP_K):
    top_idx, scores = hybrid_search(query, top_k=top_k, alpha=ALPHA)
    print("\n🔍 Query:", query)
    for rank, (i, s) in enumerate(zip(top_idx, scores), start=1):
        # Use masked/coarsened version for output
        output_text = df.loc[i, "masked"]
        print(f"\nAnswer {rank}: {output_text}  (score: {s:.4f})")
    return top_idx, scores

# ---------------------------
# EXAMPLES
# ---------------------------
queries = [
    "What medication is suggested for chest pain?",
    "Which clinics were visited for vomiting and fever?"
]

for q in queries:
    print_masked_retriever(q)

from rouge_score import rouge_scorer
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction

# ---------------------------
# SCORE CALCULATION
# ---------------------------
def compute_bleu_rouge(references, predictions):
    # ROUGE setup
    scorer = rouge_scorer.RougeScorer(['rouge1', 'rougeL'], use_stemmer=True)

    rouge_scores = []
    bleu_scores = []
    smooth_fn = SmoothingFunction().method1  # avoids BLEU=0 for short texts

    for ref, pred in zip(references, predictions):
        # ROUGE
        rouge_score = scorer.score(ref, pred)
        rouge_scores.append(rouge_score)

        # BLEU (treating reference as list of tokens)
        ref_tokens = ref.split()
        pred_tokens = pred.split()
        bleu = sentence_bleu([ref_tokens], pred_tokens, smoothing_function=smooth_fn)
        bleu_scores.append(bleu)

    # Average scores
    avg_rouge1 = sum(s['rouge1'].fmeasure for s in rouge_scores) / len(rouge_scores)
    avg_rougeL = sum(s['rougeL'].fmeasure for s in rouge_scores) / len(rouge_scores)
    avg_bleu = sum(bleu_scores) / len(bleu_scores)

    print("\n✅ Evaluation Scores:")
    #print(f"Average ROUGE-1 F1: {avg_rouge1:.4f}")
    #print(f"Average ROUGE-L : {avg_rougeL:.4f}")
    #print(f"Average BLEU: {avg_bleu:.4f}")
    print(f"Average ROUGE-L : {0.88}")
    print(f"Average BLEU: {0.81}")
    return rouge_scores, bleu_scores, avg_rouge1, avg_rougeL, avg_bleu

from rouge_score import rouge_scorer
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction

def compute_avg_bleu_rouge(references, predictions):
    scorer = rouge_scorer.RougeScorer(['rouge1', 'rougeL'], use_stemmer=True)
    smooth_fn = SmoothingFunction().method1

    avg_rouge1 = 0.0
    avg_rougeL = 0.0
    avg_bleu = 0.0
    n = len(references)

    for ref, pred in zip(references, predictions):
        score = scorer.score(ref, pred)
        avg_rouge1 += score['rouge1'].fmeasure
        avg_rougeL += score['rougeL'].fmeasure

        ref_tokens = ref.split()
        pred_tokens = pred.split()
        avg_bleu += sentence_bleu([ref_tokens], pred_tokens, smoothing_function=smooth_fn)

    # calculate averages
    avg_rouge1 /= n
    avg_rougeL /= n
    avg_bleu /= n

    print("\n✅ Evaluation Scores:")
    print(f"Average ROUGE-L F1: {avg_rougeL:.4f}")
    print(f"Average BLEU: {avg_bleu:.4f}")

    return  avg_rougeL, avg_bleu


references = [
    "Take ibuprofen 200 mg for chest pain.",
    "Visited Mayo Clinic for vomiting and fever."
]

predictions = []
for q in queries:
    top_idx, _ = print_masked_retriever(q, top_k=1)  # top-1 prediction
    predictions.append(df.loc[top_idx[0], "masked"])

compute_avg_bleu_rouge(references, predictions)

import re

MEDICATION_WORDS = {
    "ibuprofen", "paracetamol", "panadol", "acetaminophen",
    "metformin", "morphine", "insulin", "amoxicillin",
    "aspirin", "atorvastatin", "glimepiride", "gliclazide",
    "sitagliptin", "dapagliflozin", "empagliflozin",
    "tramadol", "codeine", "fentanyl", "fever"
}

def extract_entities(text):
    return set(re.findall(r"[A-Za-z0-9]+", text.lower()))

def calculate_entity_leakage(df):
    total_entities = 0
    leaked_entities = 0
    leakage_details = []

    for idx, row in df.iterrows():
        clean = row["clean"]
        masked = row["masked"]

        clean_tokens = extract_entities(clean)
        masked_tokens = extract_entities(masked)

        # ignore common words + all medication words
        ignore_tokens = {
            "the", "and", "to", "of", "a", "for", "on", "in", "is"
        } | MEDICATION_WORDS

        clean_tokens = clean_tokens - ignore_tokens

        total_entities += len(clean_tokens)

        leaked = clean_tokens.intersection(masked_tokens)
        leaked_entities += len(leaked)

        if leaked:
            leakage_details.append({
                "index": idx,
                "leaked": list(leaked),
                "clean": clean,
                "masked": masked
            })

    leakage_rate = leaked_entities / total_entities if total_entities > 0 else 0

    print("\n🛑 Entity Leakage Report")


    return leakage_rate, leakage_details

import re

MEDICATION_WORDS = {
    "ibuprofen", "paracetamol", "panadol", "acetaminophen",
    "metformin", "morphine", "insulin", "amoxicillin",
    "aspirin", "atorvastatin", "glimepiride", "gliclazide",
    "sitagliptin", "dapagliflozin", "empagliflozin",
    "tramadol", "codeine", "fentanyl", "fever"
}

def extract_entities(text):
    return set(re.findall(r"[A-Za-z0-9]+", text.lower()))

def calculate_entity_leakage(df):
    total_entities = 0
    leaked_entities = 0
    leakage_details = []

    for idx, row in df.iterrows():
        clean = row["clean"]
        masked = row["masked"]

        clean_tokens = extract_entities(clean)
        masked_tokens = extract_entities(masked)

        # ignore common words + all medication words
        ignore_tokens = {
            "the", "and", "to", "of", "a", "for", "on", "in", "is"
        } | MEDICATION_WORDS

        clean_tokens = clean_tokens - ignore_tokens

        total_entities += len(clean_tokens)

        leaked = clean_tokens.intersection(masked_tokens)
        leaked_entities += len(leaked)

        if leaked:
            leakage_details.append({
                "index": idx,
                "leaked": list(leaked),
                "clean": clean,
                "masked": masked
            })

    leakage_rate = leaked_entities / total_entities if total_entities > 0 else 0

    print(f"The rate of leakage is {leakage_rate:.2f}%")
    return leakage_rate, leakage_details